checks:
    python:
        code_rating: true
        duplicate_code: true
filter:
    excluded_paths:
        - tests/*
        - travis/*
        - example/*
tools:
    external_code_coverage:
        timeout: 1800
        runs: 15